### ISSUE TITLE
Feed language issue

### ISSUE THREAD

**Issue by AboutRSS** [abhinavmarwaha/curator#2]
Thanks for your creation. Feed in Chinese can not be resolved properly.

**Comment by abhinavmarwaha** [comment]
Thank you for letting me know.

Can you provide more information like screenshot, what were you exactly expecting, steps to reproduce the problem etc?
(I have added the issue template, you can refer that)

As I don't have adequate knowledge of internationalization and Chinese I may find difficulty fixing this but I will try my very best to research and fix this problem.

**Comment by AboutRSS** [comment]
Thanks for your response.

My test feed is http://www.people.com.cn/rss/politics.xml

Here are the screenshots:

![Screenshot_2020-09-06-21-56-47 - 副本.png](https://i.loli.net/2020/09/06/oy5Dsx6gGriAaSP.png)

![Screenshot_2020-09-06-21-57-06 - 副本.png](https://i.loli.net/2020/09/06/ndtmuepHbUyM8Aj.png)
