### ISSUE TITLE
Commafeed support

### ISSUE THREAD

**Issue by trymeouteh** [abhinavmarwaha/curator#4]
Please add support for Commafeed. Commafeed is a free, open source self hostable service to allow RSS feeds. It works great on desktop and mobile in the browser but it would be great to have a free open source Android app that supports syncing with your Commafeed account.

**Comment by abhinavmarwaha** [comment]
This app's goal was to be a standalone RSS reader and not an app dependent on an external server. So for now I won't be supporting external services.
